import { Network } from './types';
export const Networks = <Array<Network>>[
  {
    name: 'ETH',
    name_long: 'Ethereum',
    chainID: 1,
    tokens: [],
    icon: getIcon('ETH'),
    currencyName: 'ETH',
    gasPriceMultiplier: 1,
    coingeckoID: 'ethereum',
    service: 'myetherwallet.com-ws',
    url: 'wss://nodes.mewapi.io/ws/eth',
    port: 443,
    auth: false,
    username: '',
    password: '',
  },
  {
    name: 'BTC',
    name_long: 'Bitcoin',
    chainID: 1,
    tokens: [],
    icon: getIcon('BTC'),
    currencyName: 'BTC',
    gasPriceMultiplier: 1,
    coingeckoID: 'bitcoin',
    service: '',
    url: '',
    port: 443,
    auth: false,
    username: '',
    password: '',
  },
  {
    name: 'BCH',
    name_long: 'Bitcoin Cash',
    chainID: 1,
    tokens: [],
    icon: getIcon('BCH'),
    currencyName: 'BCH',
    gasPriceMultiplier: 1,
    coingeckoID: 'bitcoin-cash',
    service: '',
    url: '',
    port: 443,
    auth: false,
    username: '',
    password: '',
  },
  // {
  //   name: 'BSC',
  //   name_long: 'Binance Smart Chain',
  //   chainID: 56,
  //   tokens: [],
  //   icon: getIcon('BNB'),
  //   currencyName: 'BNB',
  //   gasPriceMultiplier: 1,
  //   coingeckoID: 'binancecoin',
  //   service: 'myetherwallet.com-ws',
  //   url: 'wss://nodes.mewapi.io/ws/bsc',
  //   port: 443,
  //   auth: false,
  //   username: '',
  //   password: '',
  // },
  {
    name: 'MATIC',
    name_long: 'Polygon (Matic)',
    chainID: 137,
    tokens: [],
    icon: getIcon('MATIC'),
    currencyName: 'MATIC',
    gasPriceMultiplier: 1.7,
    coingeckoID: 'matic-network',
    service: 'myetherwallet.com-ws',
    url: 'wss://nodes.mewapi.io/ws/matic',
    port: 443,
    auth: false,
    username: '',
    password: '',
  },
  {
    name: 'DOT',
    name_long: 'Polkadot',
    chainID: 1,
    tokens: [],
    icon: getIcon('DOT'),
    currencyName: 'DOT',
    gasPriceMultiplier: 1,
    coingeckoID: 'polkadot',
    service: '',
    url: '',
    port: 443,
    auth: false,
    username: '',
    password: '',
  },
  {
    name: 'KSM',
    name_long: 'Kusama',
    chainID: 1,
    tokens: [],
    icon: getIcon('KSM'),
    currencyName: 'KSM',
    gasPriceMultiplier: 1,
    coingeckoID: 'kusama',
    service: '',
    url: '',
    port: 443,
    auth: false,
    username: '',
    password: '',
  },
  // {
  //   name: 'LTC',
  //   name_long: 'Litecoin',
  //   chainID: 1,
  //   tokens: [],
  //   icon: getIcon('LTC'),
  //   currencyName: 'LTC',
  //   gasPriceMultiplier: 1,
  //   coingeckoID: 'litecoin',
  //   service: '',
  //   url: '',
  //   port: 443,
  //   auth: false,
  //   username: '',
  //   password: '',
  // },
  // {
  //   name: 'DOGE',
  //   name_long: 'Dogecoin',
  //   chainID: 1,
  //   tokens: [],
  //   icon: getIcon('DOGE'),
  //   currencyName: 'DOGE',
  //   gasPriceMultiplier: 1,
  //   coingeckoID: 'dogecoin',
  //   service: '',
  //   url: '',
  //   port: 443,
  //   auth: false,
  //   username: '',
  //   password: '',
  // },
  {
    name: 'KDA',
    name_long: 'Kadena',
    chainID: 1,
    tokens: [],
    icon: getIcon('KDA'),
    currencyName: 'KDA',
    gasPriceMultiplier: 1,
    coingeckoID: 'kadena',
    service: '',
    url: '',
    port: 443,
    auth: false,
    username: '',
    password: '',
  },
];

function getIcon(currency: string) {
  return require(`@/assets/images/crypto/${currency}.svg`);
}
