name: add to ccswapbuilds

on: push

jobs:
  ccswapBuild:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set node version
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: yarn install
      - run: yarn build
      - name: Deploy to S3
        if: github.base_ref == ''
        env:
          AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET}}
        run: |
          pip install --user awscli
          aws s3 sync --delete --acl public-read dist/ s3://ethvm-front-end-builds/builds/$GITHUB_SHA
          aws s3 cp s3://ethvm-front-end-builds/builds/$GITHUB_SHA/index.html s3://ethvm-front-end-builds/builds/$GITHUB_SHA/index.html \
            --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate \
            --content-type text/html --acl public-read
      - name: comment on PR
        uses: mshick/add-pr-comment@v2
        with:
          message: Copy of this build can be found at <br>https://builds.ethvm.dev/${{github.sha}}/index.html</br>
